/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GameRouteImport } from './routes/Game'
import { Route as IndexRouteImport } from './routes/index'

const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/Game',
  path: '/Game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Game': typeof GameRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/lobby': typeof LobbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Game': typeof GameRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/lobby': typeof LobbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Game': typeof GameRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/lobby': typeof LobbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Game' | '/about' | '/history' | '/lobby'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Game' | '/about' | '/history' | '/lobby'
  id: '__root__' | '/' | '/Game' | '/about' | '/history' | '/lobby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  LobbyRoute: typeof LobbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Game': {
      id: '/Game'
      path: '/Game'
      fullPath: '/Game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  LobbyRoute: LobbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
